### ISSUE TITLE
Comments are not working

### ISSUE THREAD

**Issue by jutaro** [freebroccolo/atom-language-purescript#2]
Seems it is fixed by the patch of Paul, so can you please make a new release!

**Comment by paulyoung** [comment]
Bump :pray:

**Comment by jutaro** [comment]
I guess we need to wait for a new version tag to use it. How many month will this take? Pray again please...

**Comment by jutaro** [comment]
yes pray pray pray ... we are lost finally. No update ever?

**Comment by paulyoung** [comment]
@freebroccolo :crying_cat_face:

**Comment by freebroccolo** [comment]
Sorry, I didn't see this earlier. The problem is I'm not using Atom much anymore but I'll try to make a new release later today…
