### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by sdegutis** [freebroccolo/atom-language-purescript#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/sdegutis/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
[object Object].attach (/Users/sdegutis/.atom/packages/language-purescript/node_modules/atom-message-panel/lib/MessagePanelView.js:65:9)
```

**Comment by nwolverson** [comment]
Is this fixed? I think it was maybe fixed by #4 ?

**Comment by sdegutis** [comment]
No idea, I don't use Atom or PureScript anymore, sorry.

**Comment by nwolverson** [comment]
@freebroccolo I think this can be closed as above
